const input={left:false,right:false,jump:false,attack:false,place:false};
document.getElementById("left").addEventListener("touchstart",()=>input.left=true);
document.getElementById("left").addEventListener("touchend",()=>input.left=false);
document.getElementById("right").addEventListener("touchstart",()=>input.right=true);
document.getElementById("right").addEventListener("touchend",()=>input.right=false);
document.getElementById("jump").addEventListener("touchstart",()=>input.jump=true);
document.getElementById("jump").addEventListener("touchend",()=>input.jump=false);
document.getElementById("attack").addEventListener("touchstart",()=>input.attack=true);
document.getElementById("attack").addEventListener("touchend",()=>input.attack=false);
document.getElementById("place").addEventListener("touchstart",()=>input.place=true);
document.getElementById("place").addEventListener("touchend",()=>input.place=false);
window.input=input;